services:
  # media-service:
  #   image: bluenviron/mediamtx:1.15.1
  #   container_name: media-service
  #   restart: unless-stopped
  #   environment:
  #     MTX_PATHDEFAULTS_RECORD: ${RECORD_ENABLED}
  #     MTX_PATHDEFAULTS_RECORDPATH: ${RECORD_PATH}
  #     MTX_PATHDEFAULTS_RECORDFORMAT: ${RECORD_FORMAT}
  #     MTX_PATHDEFAULTS_RECORDPARTDURATION: ${RECORD_PART_DURATION}
  #     MTX_PATHDEFAULTS_RECORDMAXPARTSIZE: ${RECORD_MAX_PART_SIZE}
  #     MTX_PATHDEFAULTS_RECORDSEGMENTDURATION: ${RECORD_SEGMENT_DURATION}
  #     MTX_PATHDEFAULTS_RECORDDELETEAFTER: ${RECORD_DELETE_AFTER}
  #     MTX_AUTHINTERNALUSERS_0_USER: ${MEDIA_USERNAME}
  #     MTX_AUTHINTERNALUSERS_0_PASS: ${MEDIA_PASSWORD}
  #     MTX_AUTHINTERNALUSERS_0_PERMISSIONS_0_ACTION: publish
  #     MTX_AUTHINTERNALUSERS_0_PERMISSIONS_1_ACTION: read
  #     MTX_AUTHINTERNALUSERS_0_PERMISSIONS_2_ACTION: playback
  #     MTX_AUTHINTERNALUSERS_0_PERMISSIONS_3_ACTION: api
  #   volumes:
  #     - ./mediamtx.yml:/mediamtx.yml
  #     - ~/record:${VIDEO_RECORD_PATH}
  #     - /etc/localtime:/etc/localtime:ro
  #     - /etc/timezone:/etc/timezone:ro
  #   networks:
  #     - default
  #   ports:
  #     - 8554:8554 
  #     - 1935:1935 
  #     - 8888:8888 
  #     - 8890:8890/udp 
  #     - 8189:8189/udp 
  #     - 8889:8889

  cctv-recorder:
    image: cctv-recorder
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
    container_name: cctv-recorder
    env_file:
      - .env
    volumes:
      - /mnt/records:${VIDEO_RECORD_PATH}
      # - ./assets:/app/assets
      - ./logs:/app/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    # depends_on:
    #   media-service:
    #     condition: service_started
  #   tty: true
    networks:
      - default

networks:
  default:
    name: rtsp_hub_network
    driver: bridge